AWSTemplateFormatVersion: 2010-09-09
Description: Neptune Playground - Infrastucture for Neptune Analytics Graph

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      BucketName: !Sub "${AWS::StackName}-data"
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            ExpiredObjectDeleteMarker: true
            NoncurrentVersionExpiration:
              NoncurrentDays: 14
      LoggingConfiguration:
        DestinationBucketName: !ImportValue infra-buckets-LogBucket
        LogFilePrefix: !Sub s3_access/bucket=${AWS::StackName}-data/
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      Tags:
        - { Key: Name, Value: !Sub "${AWS::StackName}-data" }

  Key:
    Type: AWS::KMS::Key
    Properties:
      Description: !Sub KMS key for Neptune Analytics Graph ${AWS::StackName}
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "*"
            Resource: "*"
      KeySpec: SYMMETRIC_DEFAULT
      KeyUsage: ENCRYPT_DECRYPT
      MultiRegion: false
      PendingWindowInDays: 7
      Tags:
        - { Key: Name, Value: !Sub "${AWS::StackName}-Key" }

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service:
              - export.rds.amazonaws.com
              - neptune-graph.amazonaws.com
      Policies:
        - PolicyName: AnalyticsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject*
                  - s3:DeleteObject*
                  - s3:GetBucketLocation
                  - s3:PutObject*
                Resource:
                  - !Sub ${DataBucket.Arn}
                  - !Sub ${DataBucket.Arn}/*
              - Effect: Allow
                Action:
                  - rds:DescribeDBClusters
                  - rds:DescribeDBClusterSnapshots
                  - rds:StartExportTask
                  - rds:DescribeExportTasks
                  - rds:CancelExportTask
                Resource: "*"
              - Effect: Allow
                Action:
                  - kms:CreateGrant
                  - kms:DescribeKey
                  - kms:RetireGrant
                Resource: !GetAtt Key.Arn

  PassRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: PassRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:PassRole
            Resource:
              - !GetAtt Role.Arn
      Roles:
        - !Ref Role

Outputs:
  DataBucket:
    Description: Data bucket for Neptune Analytics Graph
    Value: !Ref DataBucket
    Export:
      Name: !Sub "${AWS::StackName}-DataBucket"
  Key:
    Description: KMS key for Neptune Analytics Graph
    Value: !Ref Key
    Export:
      Name: !Sub "${AWS::StackName}-Key"
  RoleArn:
    Description: IAM role for Neptune Analytics Graph
    Value: !GetAtt Role.Arn
    Export:
      Name: !Sub "${AWS::StackName}-Role"